config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    # redirect home page to all orders
    path("", RedirectView.as_view(pattern_name="orders:all", permanent=True)),
    # order management
    path("orders/", include("shopify_app.orders.urls", namespace="orders")),
    # admin site
    path("admin/", admin.site.urls),
]

if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

shopify_app/orders/urls.py
from django.urls import path

from shopify_app.orders.views import order_create_view, order_list_view

app_name = "orders"

urlpatterns = [
    path("create/", view=order_create_view, name="create"),
    path("all/", view=order_list_view, name="all"),
]

shopify_app/orders/forms.py
from django.forms import CharField, EmailField, FloatField, Form, IntegerField


class OrderCreateForm(Form):
    email = EmailField(required=False)
    title = CharField()
    quantity = IntegerField()
    price = FloatField()

shopify_app/orders/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls.base import reverse_lazy
from django.views.generic import FormView, TemplateView

from shopify_app.orders.forms import OrderCreateForm
from shopify_app.orders.services import create_order, get_all_orders


class OrderCreateView(SuccessMessageMixin, FormView):
    template_name = "orders/order_create_form.html"
    form_class = OrderCreateForm
    success_url = reverse_lazy("orders:all")
    success_message = "Order added successfully."

    def form_valid(self, form):
        data = form.cleaned_data
        line_items = {key: data.get(key) for key in ("title", "quantity", "price")}
        email = data.get("email")
        create_order({"email": email, "line_items": [line_items]})
        return super().form_valid(form)


order_create_view = OrderCreateView.as_view()


class OrderListView(TemplateView):
    template_name = "orders/order_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["orders"] = get_all_orders()
        return context


order_list_view = OrderListView.as_view()

shopify_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Shopify App{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  {% block css %}
  <!-- Latest minified Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/materia/bootstrap.min.css" integrity="sha384-B4morbeopVCSpzeC1c4nyV0d0cqvlSAfyXVfrPJa25im5p+yEN/YmhlgQP/OyMZD" crossorigin="anonymous">
  {% endblock %}

</head>

<body>

  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">Shopify App</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:all' %}">View Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders:create' %}">Create Order</a>
          </li>
        </ul>
    </nav>
  </div>

  <div class="container">

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button"
        class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

  </div> <!-- /container -->

  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}
  <!-- jQuery JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
  {% endblock javascript %}
</body>

</html>

shopify_app/templates/orders/order_create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Order{% endblock title %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form class="form-horizontal" method="POST" action="{% url 'orders:create' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
        </form>
    </div>
  </div>
{% endblock content %}

shopify_app/templates/orders/order_list.html
{% extends "base.html" %}
{% block title %}View Orders{% endblock title %}

{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Price</th>
        <th scope="col">Currency</th>
        <th scope="col">Confirmed</th>
        <th scope="col">Processed At</th>
      </tr>
    </thead>
    <tbody>
    {% for order in orders %}
      <tr>
        <th scope="row"><a href="{{ order.order_status_url }}">{{ order.id }}</a></th>
        <td>{{ order.total_price }}</td>
        <td>{{ order.currency }}</td>
        <td>{{ order.confirmed }}</td>
        <td>{{ order.processed_at }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock content %}